### ISSUE TITLE
v3 Target API calls not working

### ISSUE THREAD

**Issue by alexandra-anton** [adobe/aio-lib-target#35]
### Expected Behaviour
Target API Calls that use the v3 Accept-header `('Accept: application/vnd.adobe.target.v3+json')` should be successful.

### Actual Behaviour
When I try to call `getABActivityById` from my code, I get this error:
```javascript
[TargetSDK:ERROR_GET_AB_ACTIVITY_BY_ID] Error: Conflict
    at _callee$ (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/swagger-client/dist/index.js:581:816)
    at tryCatch (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/regenerator-runtime/runtime.js:271:22)
    at Generator.prototype.<computed> [as next] (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:5:24)
    at _next (/Users/alexandraanton/_DATA/GIT_Repos/ADOBE-IO-TOOLS/node_modules/@babel/runtime-corejs2/helpers/asyncToGenerator.js:27:9)
    at processTicksAndRejections (internal/process/task_queues.js:94:5) {
  status: 409,
  statusCode: 409,
  response: [Object]
}
```

### Reproduce Scenario (including but not limited to)
I have code that leverages the adobe-io-target lib, and that makes calls to `getActivities`, `getABActivityById`, `getXTActivityById` as well as update activity API calls.

#### Steps to Reproduce
I have tried to fix the issue by changing the code to make another request intercept and add the necessary Accept headers. After this, it works. I am attaching the modified code here 
[index.js.zip](https://github.com/adobe/aio-lib-target/files/4307488/index.js.zip)
to give you an idea. Please have a look at getActivities, getABActivityById and getXTActivityById.

If the solution seems acceptable to you, I can create a PR to cover all API calls, otherwise please have a look and let me know your opinion.
 
#### Platform and Version
Current version

#### Sample Code that illustrates the problem
```javascript
const exportActivity = (activity) => {
  return targetApi.initApi().then((sdk) => {
    if (activity.type === 'abt') {
      console.warn(chalk.red("Skipping activity"), activity)
      return Promise.resolve(() => { })
    }
    if (activity.type === 'ab') {
      return sdk.getABActivityById(activity.id);
    }
    if (activity.type === 'xt') {
      return sdk.getXTActivityById(activity.id);
    }
  })
}
```

**Comment by meryllblanchet** [comment]
Thanks for the issue @alexandra-anton , we'll have a look.

**Comment by sandeep-paliwal** [comment]
Looking into this

**Comment by sandeep-paliwal** [comment]
Hi @alexandra-anton , thanks for sharing details about the issue and probable fix.
I have created PR based on some of the changes suggested along with tests - https://github.com/adobe/aio-lib-target/pull/36

**Comment by alexandra-anton** [comment]
Hi @sandeep-paliwal, great, thanks for the quick fix! I'll test it as soon as it's merged.

**Comment by shazron** [comment]
We've updated all the calls to have the proper `Accepts` header, coming in the next release.
